### ISSUE TITLE
balance.txt file write format in pre-release 2

### ISSUE THREAD

**Issue by s-benavides** [pmininni/GHOST#2]
Hola,

Me di cuenta que en el subroutine "hdcheck" (linea 1090 de pseudospec3D_hd.f90) dice:

   10    FORMAT( E13.6,E25.18,E25.18,E25.18 )

El ultimo tendria que decir E26.18, porque si no hay problemas cuando 'pot' < 0 y entonces no hay espacio entre las dos columnas. (por ejemplo ...9E+02-0.90242...E+01 en vez de ...9E+02 -0.90242...E+01 con espacio).

Vi que en "master" ya fue cambiado. No se en que otros archivos existe este problema. Vi que en el pseudospec3D_mhd.f90 dice E22.14, que esta bien.

Santi

**Comment by pmininni** [comment]
Thanks, this issue is now fixed!
