### ISSUE TITLE
mean.eq.1 b-field update incorrect?

### ISSUE THREAD

**Issue by s-benavides** [pmininni/GHOST#3]
Hola,

Me di cuenta que en linea 2512 de 'master' y 'pre-release-2' dice:

_________________________________
#ifdef MAGFIELD_
               CALL rotor3(ay,az,C1,1)
               CALL rotor3(ax,az,C2,2)
               CALL rotor3(ax,ay,C3,3)
!$omp parallel do if (iend-ista.ge.nth) private (j,k)
               DO i = ista,iend
!$omp parallel do if (iend-ista.lt.nth) private (k)
                  DO j = 1,n
                     DO k = 1,n
                        M4(k,j,i) = M4(k,j,i)+vx(k,j,i)
                        M5(k,j,i) = M5(k,j,i)+vy(k,j,i)
                        M6(k,j,i) = M6(k,j,i)+vz(k,j,i)
                     END DO
                  END DO
               END DO
#endif
______________________________________________________

Me imagino que tendria que decir:

                        M4(k,j,i) = M4(k,j,i)+C1(k,j,i)
                        M5(k,j,i) = M5(k,j,i)+C2(k,j,i)
                        M6(k,j,i) = M6(k,j,i)+C3(k,j,i)

No?

Santi

**Comment by pmininni** [comment]
Thanks, I just fixed this issue on 'master' and 'pre-release-2'!
